import mongoose from 'mongoose';

const TaxStatementSchema = new mongoose.Schema({
  teacherId: { type: mongoose.Schema.Types.ObjectId, ref: 'Teacher', required: true },
  financialYearId: { type: mongoose.Schema.Types.ObjectId, ref: 'FinancialYear', required: true },
  regime: { type: String, enum: ['New', 'Old'], required: true },
  type: { type: String, enum: ['Anticipatory', 'Final'], required: true },
  monthlyData: [{
    month: String,
    basicPay: Number,
    da: Number,
    hra: Number,
    ca: Number,
    otherAllowance: Number,
    pf: Number,
    gis: Number,
    sli: Number,
    lic: Number,
    medisep: Number,
    gpais: Number,
    nps: Number,
    tds: Number
  }],
  festivalAllowance: { type: Number, default: 0 },
  daArrear: { type: Number, default: 0 },
  payRevisionArrear: { type: Number, default: 0 },
  leaveSurrender: { type: Number, default: 0 },
  otherIncome: { type: Number, default: 0 },
  totalIncome: { type: Number, required: true },
  taxableIncome: { type: Number, required: true },
  taxOnTotalIncome: { type: Number, default: 0 },
  taxRebate: { type: Number, default: 0 },
  surcharge: { type: Number, default: 0 },
  cess: { type: Number, default: 0 },
  totalTax: { type: Number, default: 0 },
  taxDeducted: { type: Number, default: 0 },
  balanceTax: { type: Number, default: 0 },
  section80C: { type: Number, default: 0 },
  section80D: { type: Number, default: 0 },
  section80G: { type: Number, default: 0 },
  section80E: { type: Number, default: 0 },
  hbaInterest: { type: Number, default: 0 },
  hbaPrincipal: { type: Number, default: 0 },
  tuitionFees: { type: Number, default: 0 },
  anyOtherDeductions: { type: Number, default: 0 },
  annualPF: { type: Number, default: 0 },
  annualGIS: { type: Number, default: 0 },
  annualSLI: { type: Number, default: 0 },
  annualLIC: { type: Number, default: 0 },
  annualMedisep: { type: Number, default: 0 },
  annualGPAIS: { type: Number, default: 0 },
  annualNPS: { type: Number, default: 0 },
  annualTDS: { type: Number, default: 0 },
  status: { type: String, enum: ['Draft', 'Submitted', 'Approved'], default: 'Draft' },
  isConfirmed: { type: Boolean, default: false },
  isBasicPayUpdated: { type: Boolean, default: false },
  signedPdfUrl: String
}, { timestamps: true });

export default mongoose.model('TaxStatement', TaxStatementSchema);
